name: PR Check

on:
  pull_request:
    branches: ["main"]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Lint
        run: npx @biomejs/biome check ./src
        
      - name: Type Check
        run: npx tsc --noEmit  # 만약 TypeScript를 사용한다면 